# Generated by Django 5.0.4 on 2024-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='0', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
